<?xml version="1.0"?>
<package format="2">
  <name>my_navigation</name>
  <version>0.0.0</version>
  <description>The my_navigation package</description>
  <maintainer email="sanditya@todo.todo">sanditya</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>actionlib</depend>
  <depend>move_base_msgs</depend>
  <depend>tf</depend>
  <depend>cv_bridge</depend>
  <depend>image_geometry</depend>
  <depend>message_filters</depend>
  <depend>gmapping</depend>
  <depend>rviz</depend>

  <export>
  </export>
</package>
